// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegionSyd.Repositories.Entities;

#nullable disable

namespace RegionSyd.Repositories.Migrations
{
    [DbContext(typeof(RegionSydDBContext))]
    partial class RegionSydDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Alarm", b =>
                {
                    b.Property<int>("AlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlarmID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlarmId"), 1L, 1);

                    b.Property<int?>("BedId")
                        .HasColumnType("int")
                        .HasColumnName("BedID");

                    b.HasKey("AlarmId");

                    b.HasIndex(new[] { "BedId" }, "IX_Alarm_BedID");

                    b.ToTable("Alarm", (string)null);
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedId"), 1L, 1);

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.HasKey("BedId");

                    b.HasIndex(new[] { "RoomId" }, "IX_Bed_RoomID");

                    b.ToTable("Bed", (string)null);

                    b.HasData(
                        new
                        {
                            BedId = 1,
                            IsOccupied = false,
                            RoomId = 1
                        },
                        new
                        {
                            BedId = 2,
                            IsOccupied = false,
                            RoomId = 1
                        },
                        new
                        {
                            BedId = 3,
                            IsOccupied = false,
                            RoomId = 1
                        },
                        new
                        {
                            BedId = 4,
                            IsOccupied = false,
                            RoomId = 2
                        },
                        new
                        {
                            BedId = 5,
                            IsOccupied = false,
                            RoomId = 2
                        },
                        new
                        {
                            BedId = 6,
                            IsOccupied = false,
                            RoomId = 2
                        },
                        new
                        {
                            BedId = 7,
                            IsOccupied = false,
                            RoomId = 3
                        },
                        new
                        {
                            BedId = 8,
                            IsOccupied = false,
                            RoomId = 3
                        },
                        new
                        {
                            BedId = 9,
                            IsOccupied = false,
                            RoomId = 3
                        },
                        new
                        {
                            BedId = 10,
                            IsOccupied = false,
                            RoomId = 4
                        },
                        new
                        {
                            BedId = 11,
                            IsOccupied = false,
                            RoomId = 4
                        },
                        new
                        {
                            BedId = 12,
                            IsOccupied = false,
                            RoomId = 5
                        },
                        new
                        {
                            BedId = 13,
                            IsOccupied = false,
                            RoomId = 5
                        },
                        new
                        {
                            BedId = 14,
                            IsOccupied = false,
                            RoomId = 6
                        },
                        new
                        {
                            BedId = 15,
                            IsOccupied = false,
                            RoomId = 6
                        },
                        new
                        {
                            BedId = 16,
                            IsOccupied = false,
                            RoomId = 7
                        },
                        new
                        {
                            BedId = 17,
                            IsOccupied = false,
                            RoomId = 7
                        },
                        new
                        {
                            BedId = 18,
                            IsOccupied = false,
                            RoomId = 7
                        },
                        new
                        {
                            BedId = 19,
                            IsOccupied = false,
                            RoomId = 7
                        },
                        new
                        {
                            BedId = 20,
                            IsOccupied = false,
                            RoomId = 8
                        },
                        new
                        {
                            BedId = 21,
                            IsOccupied = false,
                            RoomId = 9
                        },
                        new
                        {
                            BedId = 22,
                            IsOccupied = false,
                            RoomId = 10
                        },
                        new
                        {
                            BedId = 23,
                            IsOccupied = false,
                            RoomId = 11
                        },
                        new
                        {
                            BedId = 24,
                            IsOccupied = false,
                            RoomId = 11
                        },
                        new
                        {
                            BedId = 25,
                            IsOccupied = false,
                            RoomId = 12
                        },
                        new
                        {
                            BedId = 26,
                            IsOccupied = false,
                            RoomId = 12
                        },
                        new
                        {
                            BedId = 27,
                            IsOccupied = false,
                            RoomId = 13
                        },
                        new
                        {
                            BedId = 28,
                            IsOccupied = false,
                            RoomId = 13
                        },
                        new
                        {
                            BedId = 29,
                            IsOccupied = false,
                            RoomId = 14
                        },
                        new
                        {
                            BedId = 30,
                            IsOccupied = false,
                            RoomId = 14
                        },
                        new
                        {
                            BedId = 31,
                            IsOccupied = false,
                            RoomId = 14
                        },
                        new
                        {
                            BedId = 32,
                            IsOccupied = false,
                            RoomId = 15
                        },
                        new
                        {
                            BedId = 33,
                            IsOccupied = false,
                            RoomId = 16
                        },
                        new
                        {
                            BedId = 34,
                            IsOccupied = true,
                            RoomId = 11
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"), 1L, 1);

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<DateTime?>("TreatmentEnd")
                        .HasColumnType("datetime");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int")
                        .HasColumnName("TreatmentID");

                    b.Property<int>("TreatmentPlaceId")
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceID");

                    b.Property<DateTime>("TreatmentStart")
                        .HasColumnType("datetime");

                    b.HasKey("BookingId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Booking_PatientID");

                    b.HasIndex(new[] { "TreatmentId" }, "IX_Booking_TreatmentID");

                    b.HasIndex(new[] { "TreatmentPlaceId" }, "IX_Booking_TreatmentPlaceID");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TreatmentPlaceId")
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceID");

                    b.HasKey("DepartmentId");

                    b.HasIndex(new[] { "TreatmentPlaceId" }, "IX_Department_TreatmentPlaceID");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Røntgen Afdeling",
                            TreatmentPlaceId = 1
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Søvnambulatoriet",
                            TreatmentPlaceId = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Høreklinniken",
                            TreatmentPlaceId = 1
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Blodprøve",
                            TreatmentPlaceId = 2
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeTypeID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Employee_DepartmentID");

                    b.HasIndex(new[] { "EmployeeTypeId" }, "IX_Employee_EmployeeTypeID");

                    b.HasIndex(new[] { "UserId" }, "IX_Employee_UserID");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            EmployeeCode = "marmag71",
                            EmployeeTypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            EmployeeCode = "sigsig94",
                            EmployeeTypeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            EmployeeCode = "emmell91",
                            EmployeeTypeId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 4,
                            EmployeeCode = "trotho77",
                            EmployeeTypeId = 2,
                            UserId = 4
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 1,
                            EmployeeCode = "winwol87",
                            EmployeeTypeId = 3,
                            UserId = 5
                        },
                        new
                        {
                            EmployeeId = 6,
                            DepartmentId = 3,
                            EmployeeCode = "robree66",
                            EmployeeTypeId = 3,
                            UserId = 6
                        },
                        new
                        {
                            EmployeeId = 7,
                            DepartmentId = 4,
                            EmployeeCode = "nadnis96",
                            EmployeeTypeId = 4,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTypeId"), 1L, 1);

                    b.Property<string>("EmployeeTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeType", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeTypeId = 1,
                            EmployeeTypeName = "Hospitals Læge"
                        },
                        new
                        {
                            EmployeeTypeId = 2,
                            EmployeeTypeName = "Praktiserende Læge"
                        },
                        new
                        {
                            EmployeeTypeId = 3,
                            EmployeeTypeName = "Sygeplejerske"
                        },
                        new
                        {
                            EmployeeTypeId = 4,
                            EmployeeTypeName = "Sundhedshjælper"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.FileType", b =>
                {
                    b.Property<int>("FileTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileTypeId"), 1L, 1);

                    b.Property<string>("FileTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FileTypeId");

                    b.ToTable("FileType", (string)null);

                    b.HasData(
                        new
                        {
                            FileTypeId = 1,
                            FileTypeName = "png"
                        },
                        new
                        {
                            FileTypeId = 2,
                            FileTypeName = "pdf"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JournalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalId"), 1L, 1);

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("JournalId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Journal_PatientID");

                    b.ToTable("Journal", (string)null);

                    b.HasData(
                        new
                        {
                            JournalId = 1,
                            PatientId = 1
                        },
                        new
                        {
                            JournalId = 2,
                            PatientId = 2
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntry", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JournalEntryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalEntryId"), 1L, 1);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("JournalEntryStatusId")
                        .HasColumnType("int")
                        .HasColumnName("JournalEntryStatusID");

                    b.Property<int>("JournalId")
                        .HasColumnType("int")
                        .HasColumnName("JournalID");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime");

                    b.Property<int>("TreatmentPlaceId")
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceID");

                    b.HasKey("JournalEntryId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_JournalEntry_DepartmentID");

                    b.HasIndex(new[] { "JournalEntryStatusId" }, "IX_JournalEntry_JournalEntryStatusID");

                    b.HasIndex(new[] { "JournalId" }, "IX_JournalEntry_JournalID");

                    b.HasIndex(new[] { "TreatmentPlaceId" }, "IX_JournalEntry_TreatmentPlaceID");

                    b.ToTable("JournalEntry", (string)null);

                    b.HasData(
                        new
                        {
                            JournalEntryId = 1,
                            DateAdded = new DateTime(2021, 7, 24, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Patient klager over søvnbesvær",
                            JournalEntryStatusId = 1,
                            JournalId = 1,
                            LastEdited = new DateTime(2022, 8, 31, 13, 26, 55, 904, DateTimeKind.Utc).AddTicks(2962),
                            TreatmentPlaceId = 2
                        },
                        new
                        {
                            JournalEntryId = 2,
                            DateAdded = new DateTime(2017, 2, 27, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Description = "Patient vil gerne vide om de har mangel på D vitamin",
                            JournalEntryStatusId = 1,
                            JournalId = 1,
                            LastEdited = new DateTime(2022, 8, 31, 13, 26, 55, 904, DateTimeKind.Utc).AddTicks(2977),
                            TreatmentPlaceId = 2
                        },
                        new
                        {
                            JournalEntryId = 3,
                            DateAdded = new DateTime(2022, 2, 27, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Description = "Patient har svært ved at høre",
                            JournalEntryStatusId = 2,
                            JournalId = 2,
                            LastEdited = new DateTime(2022, 8, 31, 13, 26, 55, 904, DateTimeKind.Utc).AddTicks(3012),
                            TreatmentPlaceId = 1
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("FileNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FileTypeID");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int")
                        .HasColumnName("JournalEntryID");

                    b.HasKey("FileId");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_JournalEntryFile_EmployeeID");

                    b.HasIndex(new[] { "FileTypeId" }, "IX_JournalEntryFile_FileTypeID");

                    b.HasIndex(new[] { "JournalEntryId" }, "IX_JournalEntryFile_JournalEntryID");

                    b.ToTable("JournalEntryFile", (string)null);
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"), 1L, 1);

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int")
                        .HasColumnName("JournalEntryID");

                    b.Property<DateTime?>("LastEdited")
                        .HasColumnType("datetime");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("NoteId");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_JournalEntryNote_EmployeeID");

                    b.HasIndex(new[] { "JournalEntryId" }, "IX_JournalEntryNote_JournalEntryID");

                    b.ToTable("JournalEntryNote", (string)null);

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            EmployeeId = 2,
                            IsApproved = false,
                            JournalEntryId = 1,
                            NoteContent = "har givet rådgivning om brug af mobiltelefoner før sengetid"
                        },
                        new
                        {
                            NoteId = 2,
                            EmployeeId = 2,
                            IsApproved = false,
                            JournalEntryId = 1,
                            NoteContent = "patient mener de lider af søvnapnø, har givet CPAP-maskine med hjem til at måle det"
                        },
                        new
                        {
                            NoteId = 3,
                            EmployeeId = 2,
                            IsApproved = false,
                            JournalEntryId = 1,
                            NoteContent = "CPAP-maskine viser ikke tegn på søvnapnø"
                        },
                        new
                        {
                            NoteId = 4,
                            EmployeeId = 4,
                            IsApproved = false,
                            JournalEntryId = 2,
                            NoteContent = "Henvist patient til at få taget en blodprøve"
                        },
                        new
                        {
                            NoteId = 5,
                            EmployeeId = 4,
                            IsApproved = false,
                            JournalEntryId = 2,
                            NoteContent = "Måling viser mangel på vitamin D, gevet rådgivning om tilskud"
                        },
                        new
                        {
                            NoteId = 6,
                            EmployeeId = 3,
                            IsApproved = false,
                            JournalEntryId = 3,
                            NoteContent = "Udført undersøgelse af hørsel, anbefaler høreapparat"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryStatus", b =>
                {
                    b.Property<int>("JournalEntryStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JournalEntryStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalEntryStatusId"), 1L, 1);

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JournalEntryStatusId");

                    b.ToTable("JournalEntryStatus", (string)null);

                    b.HasData(
                        new
                        {
                            JournalEntryStatusId = 1,
                            StatusName = "Igang"
                        },
                        new
                        {
                            JournalEntryStatusId = 2,
                            StatusName = "Afsluttet"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Monitor", b =>
                {
                    b.Property<int>("MonitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MonitorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitorId"), 1L, 1);

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("MonitorId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Monitor_PatientID");

                    b.ToTable("Monitor", (string)null);
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int?>("BedId")
                        .HasColumnType("int")
                        .HasColumnName("BedID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PatientId");

                    b.HasIndex("BedId");

                    b.HasIndex(new[] { "UserId" }, "IX_Patient_UserID");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            UserId = 9
                        },
                        new
                        {
                            PatientId = 2,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.HasKey("RoomId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Room_DepartmentID");

                    b.ToTable("Room", (string)null);

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 3,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 5,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            DepartmentId = 1
                        },
                        new
                        {
                            RoomId = 7,
                            DepartmentId = 2
                        },
                        new
                        {
                            RoomId = 8,
                            DepartmentId = 2
                        },
                        new
                        {
                            RoomId = 9,
                            DepartmentId = 2
                        },
                        new
                        {
                            RoomId = 10,
                            DepartmentId = 2
                        },
                        new
                        {
                            RoomId = 11,
                            DepartmentId = 2
                        },
                        new
                        {
                            RoomId = 12,
                            DepartmentId = 3
                        },
                        new
                        {
                            RoomId = 13,
                            DepartmentId = 3
                        },
                        new
                        {
                            RoomId = 14,
                            DepartmentId = 3
                        },
                        new
                        {
                            RoomId = 15,
                            DepartmentId = 3
                        },
                        new
                        {
                            RoomId = 16,
                            DepartmentId = 4
                        },
                        new
                        {
                            RoomId = 17,
                            DepartmentId = 4
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreatmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<int>("TreatmentDuration")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TreatmentId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Treatment_DepartmentID");

                    b.ToTable("Treatment", (string)null);

                    b.HasData(
                        new
                        {
                            TreatmentId = 1,
                            DepartmentId = 4,
                            TreatmentDuration = 15,
                            TreatmentName = "Blodprøve"
                        },
                        new
                        {
                            TreatmentId = 2,
                            DepartmentId = 3,
                            TreatmentDuration = 45,
                            TreatmentName = "Høreprøve"
                        },
                        new
                        {
                            TreatmentId = 3,
                            DepartmentId = 4,
                            TreatmentDuration = 15,
                            TreatmentName = "Blodprøve"
                        },
                        new
                        {
                            TreatmentId = 4,
                            DepartmentId = 1,
                            TreatmentDuration = 60,
                            TreatmentName = "CT-scanning"
                        },
                        new
                        {
                            TreatmentId = 5,
                            DepartmentId = 2,
                            TreatmentDuration = 60,
                            TreatmentName = "Polysomnografi"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.TreatmentPlace", b =>
                {
                    b.Property<int>("TreatmentPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentPlaceId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TreatmentPlaceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TreatmentPlaceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceTypeID");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("TreatmentPlaceId");

                    b.HasIndex(new[] { "TreatmentPlaceTypeId" }, "IX_TreatmentPlace_TreatmentPlaceTypeID");

                    b.ToTable("TreatmentPlace", (string)null);

                    b.HasData(
                        new
                        {
                            TreatmentPlaceId = 1,
                            Address = "Kresten Philipsens Vej 15",
                            City = "Aabenraa",
                            TreatmentPlaceName = "Sygehus Sønderjylland",
                            TreatmentPlaceTypeId = 1,
                            ZipCode = 6200
                        },
                        new
                        {
                            TreatmentPlaceId = 2,
                            Address = "Ulsnæs 13",
                            City = "Gråsten",
                            TreatmentPlaceName = "Sundhedshus Gråsten",
                            TreatmentPlaceTypeId = 2,
                            ZipCode = 6300
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.TreatmentPlaceType", b =>
                {
                    b.Property<int>("TreatmentPlaceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TreatmentPlaceTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentPlaceTypeId"), 1L, 1);

                    b.Property<string>("TreatmentPlaceTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TreatmentPlaceTypeId");

                    b.ToTable("TreatmentPlaceType", (string)null);

                    b.HasData(
                        new
                        {
                            TreatmentPlaceTypeId = 1,
                            TreatmentPlaceTypeName = "Sygehus"
                        },
                        new
                        {
                            TreatmentPlaceTypeId = 2,
                            TreatmentPlaceTypeName = "Sundhedshus"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cpr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "UserTypeId" }, "IX_User_UserTypeID");

                    b.HasIndex(new[] { "Cpr" }, "UK_CPR")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Vesterbrogade 1",
                            CityName = "Aabenraa",
                            Cpr = "050871-1595",
                            Email = "marmag71@regionsyd.dk",
                            FirstName = "Martin",
                            LastName = "Magnussen",
                            Phone = "19191919",
                            UserTypeId = 1,
                            Username = "Marmag",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Vesterbrogade 2",
                            CityName = "Aabenraa",
                            Cpr = "010394-4718",
                            Email = "sigsig94@regionsyd.dk",
                            FirstName = "Sigrid",
                            LastName = "Sigurtsen",
                            Phone = "17171717",
                            UserTypeId = 1,
                            Username = "Sigsig",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Vesterbrogade 3",
                            CityName = "Aabenraa",
                            Cpr = "090991-5628",
                            Email = "emmell91@regionsyd.dk",
                            FirstName = "Emma",
                            LastName = "Ellert",
                            Phone = "14141414",
                            UserTypeId = 1,
                            Username = "Emmell",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 4,
                            Address = "Vesterbrogade 4",
                            CityName = "Aabenraa",
                            Cpr = "090477-2345",
                            Email = "trotho77@regionsyd.dk",
                            FirstName = "Troels",
                            LastName = "Thomsem",
                            Phone = "24242424",
                            UserTypeId = 1,
                            Username = "Trotho",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 5,
                            Address = "Vesterbrogade 5",
                            CityName = "Aabenraa",
                            Cpr = "280587-2566",
                            Email = "winwol87@regionsyd.dk",
                            FirstName = "Winnie",
                            LastName = "Wolfsen",
                            Phone = "28282828",
                            UserTypeId = 1,
                            Username = "Winwol",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 6,
                            Address = "Vesterbrogade 6",
                            CityName = "Aabenraa",
                            Cpr = "300666-2175",
                            Email = "robree66@regionsyd.dk",
                            FirstName = "Robert",
                            LastName = "Reesen",
                            Phone = "31313131",
                            UserTypeId = 1,
                            Username = "Robree",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 7,
                            Address = "Vesterbrogade 7",
                            CityName = "Aabenraa",
                            Cpr = "110296-1232",
                            Email = "nadnis96@regionsyd.dk",
                            FirstName = "Nadja",
                            LastName = "Nissen",
                            Phone = "35353535",
                            UserTypeId = 1,
                            Username = "Nadnis",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 8,
                            Address = "Vesterbrogade 8",
                            CityName = "Aabenraa",
                            Cpr = "230164-3457",
                            Email = "iamthebest6969@ofir.dk",
                            FirstName = "Poul",
                            LastName = "Pedersen",
                            Phone = "44444444",
                            UserTypeId = 2,
                            Username = "PoulPedersen3",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 9,
                            Address = "Vesterbrogade 9",
                            CityName = "Aabenraa",
                            Cpr = "250502-3568",
                            Email = "loooouiiise@hotmail.dk",
                            FirstName = "Louise",
                            LastName = "Lundsen",
                            Phone = "40404040",
                            UserTypeId = 2,
                            Username = "Louiselundsen1",
                            ZipCode = 6200
                        },
                        new
                        {
                            UserId = 10,
                            Address = "Vesterbrogade 10",
                            CityName = "Aabenraa",
                            Cpr = "190199-2385",
                            Email = "xXxsupermanxXx@yahoo.dk",
                            FirstName = "Kim",
                            LastName = "Kold",
                            Phone = "57575757",
                            UserTypeId = 2,
                            Username = "Kimkold",
                            ZipCode = 6200
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"), 1L, 1);

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType", (string)null);

                    b.HasData(
                        new
                        {
                            UserTypeId = 1,
                            UserTypeName = "Sundhedsmedarbejder"
                        },
                        new
                        {
                            UserTypeId = 2,
                            UserTypeName = "Patient"
                        });
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Alarm", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Bed", "Bed")
                        .WithMany("Alarms")
                        .HasForeignKey("BedId")
                        .HasConstraintName("FK_Alarm_Bed");

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Bed", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Bed_Room");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Booking", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Patient");

                    b.HasOne("RegionSyd.Repositories.Entities.Treatment", "Treatment")
                        .WithMany("Bookings")
                        .HasForeignKey("TreatmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Treatment");

                    b.HasOne("RegionSyd.Repositories.Entities.TreatmentPlace", "TreatmentPlace")
                        .WithMany("Bookings")
                        .HasForeignKey("TreatmentPlaceId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_TreatmentPlace");

                    b.Navigation("Patient");

                    b.Navigation("Treatment");

                    b.Navigation("TreatmentPlace");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Department", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.TreatmentPlace", "TreatmentPlace")
                        .WithMany("Departments")
                        .HasForeignKey("TreatmentPlaceId")
                        .IsRequired()
                        .HasConstraintName("FK_Department_TreatmentPlace");

                    b.Navigation("TreatmentPlace");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Employee", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Department");

                    b.HasOne("RegionSyd.Repositories.Entities.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeType");

                    b.HasOne("RegionSyd.Repositories.Entities.User", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_User");

                    b.Navigation("Department");

                    b.Navigation("EmployeeType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Journal", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Patient", "Patient")
                        .WithMany("Journals")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Journal_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntry", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Department", "Department")
                        .WithMany("JournalEntries")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("RegionSyd.Repositories.Entities.JournalEntryStatus", "JournalEntryStatus")
                        .WithMany("JournalEntries")
                        .HasForeignKey("JournalEntryStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntry_JournalEntryStatus");

                    b.HasOne("RegionSyd.Repositories.Entities.Journal", "Journal")
                        .WithMany("JournalEntries")
                        .HasForeignKey("JournalId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntry_Journal");

                    b.HasOne("RegionSyd.Repositories.Entities.TreatmentPlace", "TreatmentPlace")
                        .WithMany("JournalEntries")
                        .HasForeignKey("TreatmentPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Journal");

                    b.Navigation("JournalEntryStatus");

                    b.Navigation("TreatmentPlace");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryFile", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Employee", "Employee")
                        .WithMany("JournalEntryFiles")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntryFile_Employee");

                    b.HasOne("RegionSyd.Repositories.Entities.FileType", "FileType")
                        .WithMany("JournalEntryFiles")
                        .HasForeignKey("FileTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntryFile_FileType");

                    b.HasOne("RegionSyd.Repositories.Entities.JournalEntry", "JournalEntry")
                        .WithMany("JournalEntryFiles")
                        .HasForeignKey("JournalEntryId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntryFile_JournalEntry");

                    b.Navigation("Employee");

                    b.Navigation("FileType");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryNote", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Employee", "Employee")
                        .WithMany("JournalEntryNotes")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntryNote_Employee");

                    b.HasOne("RegionSyd.Repositories.Entities.JournalEntry", "JournalEntry")
                        .WithMany("JournalEntryNotes")
                        .HasForeignKey("JournalEntryId")
                        .IsRequired()
                        .HasConstraintName("FK_JournalEntryNote_JournalEntry");

                    b.Navigation("Employee");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Monitor", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Patient", "Patient")
                        .WithMany("Monitors")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_Monitor_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Patient", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Bed", "Bed")
                        .WithMany("Patients")
                        .HasForeignKey("BedId")
                        .HasConstraintName("FK_Patient_Bed");

                    b.HasOne("RegionSyd.Repositories.Entities.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_User");

                    b.Navigation("Bed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Room", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Treatment", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.Department", "Department")
                        .WithMany("Treatments")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Treatment_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.TreatmentPlace", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.TreatmentPlaceType", "TreatmentPlaceType")
                        .WithMany("TreatmentPlaces")
                        .HasForeignKey("TreatmentPlaceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_TreatmentPlace_TreatmentPlaceType");

                    b.Navigation("TreatmentPlaceType");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.User", b =>
                {
                    b.HasOne("RegionSyd.Repositories.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_User_UserType");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Bed", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JournalEntries");

                    b.Navigation("Rooms");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Employee", b =>
                {
                    b.Navigation("JournalEntryFiles");

                    b.Navigation("JournalEntryNotes");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.FileType", b =>
                {
                    b.Navigation("JournalEntryFiles");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Journal", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntry", b =>
                {
                    b.Navigation("JournalEntryFiles");

                    b.Navigation("JournalEntryNotes");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.JournalEntryStatus", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Journals");

                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Room", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.Treatment", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.TreatmentPlace", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Departments");

                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.TreatmentPlaceType", b =>
                {
                    b.Navigation("TreatmentPlaces");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.User", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("RegionSyd.Repositories.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
